"""empty message

Revision ID: 2bdf804feda1
Revises: dd6d7004dda2
Create Date: 2021-02-15 20:49:22.007003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bdf804feda1'
down_revision = 'dd6d7004dda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    #Link to systems table
    op.add_column('performance_profile', sa.Column('system_id', sa.Integer(), nullable=False))
    op.create_foreign_key('performance_profile_system_id_fkey', 'performance_profile', 'systems', ['system_id'], ['id'])

    # Remove old key columns
    op.drop_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', type_='unique')
    op.drop_constraint('performance_profile_pkey', 'performance_profile')
    op.drop_column('performance_profile', 'id')
    op.drop_column('performance_profile', 'inventory_id')

    # Modify create new primary key column
    op.create_primary_key('performance_profile_pkey', 'performance_profile', ['system_id', 'report_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('performance_profile_pkey', 'performance_profile')

    op.add_column('performance_profile', sa.Column('inventory_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('performance_profile', sa.Column('id', postgresql.INTEGER(), autoincrement=True, nullable=False))

    op.create_unique_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', ['inventory_id', 'report_date'])
    op.create_primary_key('performance_profile_pkey', 'performance_profile', ['id'])

    op.drop_constraint('performance_profile_system_id_fkey', 'performance_profile')
    op.drop_column('performance_profile', 'system_id')
    # ### end Alembic commands ###
